name = "ai-cactus"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[build]
command = "npm run build"
output_dir = ".next"

[build.environment]
NODE_VERSION = "20.11.1"

[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = ".next" 