name = "ai-cactus"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_dir = "./out"

[build.environment]
NODE_VERSION = "20.11.1"

[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = "./out" 